-- begin BIKEWORKSHOP_CLIENT
create unique index IDX_BIKEWORKSHOP_CLIENT_UNIQ_EMAIL on BIKEWORKSHOP_CLIENT (EMAIL) ^
create unique index IDX_BIKEWORKSHOP_CLIENT_UNIQ_PHONE on BIKEWORKSHOP_CLIENT (PHONE) ^
-- end BIKEWORKSHOP_CLIENT
-- begin BIKEWORKSHOP_WORKER
alter table BIKEWORKSHOP_WORKER add constraint FK_BIKEWORKSHOP_WORKER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BIKEWORKSHOP_WORKER_ON_USER on BIKEWORKSHOP_WORKER (USER_ID)^
-- end BIKEWORKSHOP_WORKER
-- begin BIKEWORKSHOP_SPARE_PART
create unique index IDX_BIKEWORKSHOP_SPARE_PART_UNIQ_TITLE on BIKEWORKSHOP_SPARE_PART (TITLE) ^
-- end BIKEWORKSHOP_SPARE_PART
-- begin BIKEWORKSHOP_ORDER
alter table BIKEWORKSHOP_ORDER add constraint FK_BIKEWORKSHOP_ORDER_ON_CLIENT foreign key (CLIENT_ID) references BIKEWORKSHOP_CLIENT(ID)^
alter table BIKEWORKSHOP_ORDER add constraint FK_BIKEWORKSHOP_ORDER_ON_WORKER foreign key (WORKER_ID) references BIKEWORKSHOP_WORKER(ID)^
create index IDX_BIKEWORKSHOP_ORDER_ON_CLIENT on BIKEWORKSHOP_ORDER (CLIENT_ID)^
create index IDX_BIKEWORKSHOP_ORDER_ON_WORKER on BIKEWORKSHOP_ORDER (WORKER_ID)^
-- end BIKEWORKSHOP_ORDER
-- begin BIKEWORKSHOP_ORDER_SPARE_PART_LINK
alter table BIKEWORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_ORDSPAPAR_ON_ORDER foreign key (ORDER_ID) references BIKEWORKSHOP_ORDER(ID)^
alter table BIKEWORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_ORDSPAPAR_ON_SPARE_PART foreign key (SPARE_PART_ID) references BIKEWORKSHOP_SPARE_PART(ID)^
-- end BIKEWORKSHOP_ORDER_SPARE_PART_LINK
