-- begin WORKSHOP_ORDER
alter table WORKSHOP_ORDER add constraint FK_WORKSHOP_ORDER_ON_CLIENT foreign key (CLIENT_ID) references WORKSHOP_CLIENT(ID)^
alter table WORKSHOP_ORDER add constraint FK_WORKSHOP_ORDER_ON_WORKER foreign key (WORKER_ID) references WORKSHOP_WORKER(ID)^
create index IDX_WORKSHOP_ORDER_ON_CLIENT on WORKSHOP_ORDER (CLIENT_ID)^
create index IDX_WORKSHOP_ORDER_ON_WORKER on WORKSHOP_ORDER (WORKER_ID)^
-- end WORKSHOP_ORDER
-- begin WORKSHOP_ORDER_SPARE_PART_LINK
alter table WORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_ORDSPAPAR_ON_SPARE_PART foreign key (SPARE_PART_ID) references WORKSHOP_SPARE_PART(ID)^
alter table WORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_ORDSPAPAR_ON_ORDER foreign key (ORDER_ID) references WORKSHOP_ORDER(ID)^
-- end WORKSHOP_ORDER_SPARE_PART_LINK
-- begin WORKSHOP_WORKER
alter table WORKSHOP_WORKER add constraint FK_WORKSHOP_WORKER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_WORKSHOP_WORKER_ON_USER on WORKSHOP_WORKER (USER_ID)^
-- end WORKSHOP_WORKER
